### ISSUE TITLE
[ERROR] cublas

### ISSUE THREAD

**Issue by tchereau** [Atome-FE/llama-node#73]
since I compiled for using cuda core
first I had to add `nGpuLayers` (seem logic as it's an option available in llama.cpp)

then I obtain this error:

```
TypeError: this.instance.inference is not a function                                                    │
    at file:///root/git/llama-selfbot/node_modules/llama-node/dist/llm/llama-cpp.js:54:23               │
    at new Promise (<anonymous>)                                                                        │
    at LLamaCpp.<anonymous> (file:///root/git/llama-selfbot/node_modules/llama-node/dist/llm/llama-cpp.j│
s:53:14)                                                                                                │
    at Generator.next (<anonymous>)                                                                     │
    at file:///root/git/llama-selfbot/node_modules/llama-node/dist/llm/llama-cpp.js:33:61               │
    at new Promise (<anonymous>)                                                                        │
    at __async (file:///root/git/llama-selfbot/node_modules/llama-node/dist/llm/llama-cpp.js:17:10)     │
    at LLamaCpp.createCompletion (file:///root/git/llama-selfbot/node_modules/llama-node/dist/llm/llama-│
cpp.js:50:12)                                                                                           │
    at LLM.<anonymous> (/root/git/llama-selfbot/node_modules/llama-node/dist/index.cjs:56:23)           │
    at Generator.next (<anonymous>)
```

did I missed something or did something wrong ?

**Comment by hlhr202** [comment]
emmm, maybe your llama-node dist is still in old version
could you try to run `pnpm build` under root folder?

**Comment by TekSiDoT** [comment]
Same issue here, attempting to use 0.1.15 of both llama-node and llama-cpp with ggml q5_1 versions of different models, it looks like Llama is not properly initialized.

**Comment by TekSiDoT** [comment]
This is probably caused by synchronously calling ```llama.load(config);```.

Properly awaiting this async generator solves the problem.
